# Based on: https://jekyllrb.com/docs/continuous-integration/

language: ruby
rvm:
- 2.2
- 2.3
- ruby-head

before_script:
 - chmod +x ./tools/cibuild

script: ./tools/cibuild

# branch whitelist, only for GitHub Pages
branches:
  except:
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
