name: Ben Eills
markdown: redcarpet
highlighter: pygments

exclude: [_docker_site, conf, docker, tools, vendor, Gemfile, Gemfile.lock, README.md]

permalink: ":title/"

redcarpet:
    extensions: [with_toc_data]
