name: Ben Eills
markdown: redcarpet
highlighter: pygments

destination: docs/

exclude: [conf, docker, docs, tools, vendor, Gemfile, Gemfile.lock, README.md]

permalink: ":title/"

redcarpet:
    extensions: [with_toc_data]
