name: Ben Eills
markdown: redcarpet
highlighter: pygments

exclude: [conf, tools, vendor, Dockerfile, Gemfile, Gemfile.lock, README.md]

permalink: ":title/"

redcarpet:
    extensions: [with_toc_data]
